#!/usr/bin/python
#
# Produce example JSON to be POSTed to authbackend
#
#
# HSM> keyload
# 00002000,2000200020002000200020002000200020002000200020002000200020002000
# HSM> keycommit
#
# $ ./example-json | curl --data-urlencode request@- -v localhost:8080/authenticate
#

import sys
import json
import bcrypt

auth = True

if len(sys.argv) == 2:
    if sys.argv[1] == 'set':
        auth = False
    else:
        sys.stderr.write("Unknown command {!r}\n".format(sys.argv[1]))
        sys.exit(1)

bcrypt_salt = '$2a$08$Ahy51oCM6Vg6d.1ScOPxse'
bcrypt_plaintext = 'plaintext'
bcrypt_hashed = bcrypt.hashpw(bcrypt_plaintext, bcrypt_salt)
# withhold bcrypt salt from authentication backends
H1 = bcrypt_hashed[len(bcrypt_salt):]

sys.stderr.write("Full bcrypt hash : {!r}\n".format(bcrypt_hashed))

action = 'auth'
if not auth:
    action = 'add_creds'

a = {action:
         {'version': 1,
          'user_id': 'ft@example.net',
          'factors': [
            {'type': 'password',
             'H1': H1,
             'credential_id': 4711,
             }
            ]
          }
     }

print json.dumps(a, sort_keys=True, indent=4)
