#!/usr/bin/python
#
# Produce example JSON to be POSTed to authbackend
#
#
# HSM> keyload
# 00002000,2000200020002000200020002000200020002000200020002000200020002000
# HSM> keycommit
#
# $ ./example-json | curl --data-urlencode request@- -v localhost:8080/authenticate
#

import sys
import json
import bcrypt
from hashlib import sha512

auth = True

if len(sys.argv) == 2:
    if sys.argv[1] == 'set':
        auth = False
    else:
        sys.stderr.write("Unknown command {!r}\n".format(sys.argv[1]))
        sys.exit(1)

credential_id = '4711'
salt = 'aa' * 16
plaintext = 'plaintext'
T1 = "{!s}{!s}{!s}{!s}".format(len(credential_id), credential_id, len(plaintext), plaintext)
H1 = bcrypt.kdf(T1, salt, 32, 32).encode('hex')

sys.stderr.write("   Credential id : {!r}\n".format(credential_id))
sys.stderr.write("       Plaintext : {!r}\n".format(plaintext))
sys.stderr.write("       Formatted : {!r}\n".format(T1))
sys.stderr.write("            Salt : {!r}\n".format(salt))
sys.stderr.write("              H1 : {!r}\n".format(H1))
sys.stderr.write("\n\n")

action = 'auth'
if not auth:
    action = 'add_creds'

a = {action:
         {'version': 1,
          'user_id': 'ft@example.net',
          'factors': [
            {'type': 'password',
             'H1': H1,
             'credential_id': credential_id,
             }
            ]
          }
     }

print json.dumps(a, sort_keys=True, indent=4)
